{
 "title": "Monitoring Dashboard For mini-db",
 "time": { "from": "2024-07-15T16:41:17.382Z", "to": "2024-07-15T17:03:00.608Z" },
 "panels": [
  {
   "title": "Request Rate Panel:",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(requests_total[1m])" }
   ]
  },
  {
   "title": "CPU Usage Pane",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[1m])) by (instance)",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Goroutines Panel",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "Goroutines" }
   ]
  },
  {
   "title": "Memory Usage Panel",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "Memory Usage" }
   ]
  },
  {
   "title": "General Requests and Usage Panel",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(promhttp_metric_handler_requests_total[5m])",
     "legendFormat": "Request Rate/5min"
    },
    {
     "expr": "sum(requests_total) by (method)\r",
     "legendFormat": "Request Rate"
    },
    { "expr": "rate(requests_total[1m])\r", "legendFormat": "Total Requests/min" },
    { "expr": "rate(errors_total[1m])\r", "legendFormat": "Error Rate" },
    {
     "expr": "sum(rate(process_cpu_seconds_total[1m])) by (instance)\r",
     "legendFormat": "CPU Usage"
    },
    { "expr": "go_goroutines\r", "legendFormat": "Number of Goroutines" },
    { "expr": "go_memstats_heap_alloc_bytes\r", "legendFormat": "Heap Allocation" }
   ]
  }
 ]
}