server:
  port: "8080"
  tls: false
  tls_cert_file: "path/to/server.crt"
  tls_key_file: "path/to/server.key"

storage:
  file_path: "data/db.parquet"

logging:
  level: "info"

security:
  auth_enabled: false
  auth_token: "incognia"