name: cd

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod tidy

      - name: Build the app using build.sh
        run: |
          chmod +x ./build.sh
          ./build.sh build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create Docker network
        run: docker network create mini-db-network || true

      - name: Build and run Docker Compose for the server
        run: docker-compose up --build -d

      - name: Build and run Docker Compose for monitoring
        run: docker-compose -f monitoring/docker-compose.monitoring.yml up --build -d
